bug: Fix mirroring script feat: Add mirroring to Github bug: Fix return code from switchboot --perm feat: Remove dependency on bash maint: Fix Makefile to be compatibel with Yocto build feat:directories: Change installation paths from /opt/unipi to usual places feat:verbose: Disable console output if --verbose is not set. feat:80-ram-overcommit.conf: Add sysctl file to disable memory overcommit Add missing repo key unipi_trixie.asc feat:unipi_next.asc: Change public key for Unipi Apt repo feat:os-configurator: Emphasize reboot message by color feat:os-configurator.py: Add parameter --verbose to os-configurator Squashed 'unipi-hardware-id/' content bootcount: Fix uninitialized variable Fix unipiid tool Build for Trixie feat:uhelper Add UHELPER_LINK env variable checking feat:os-configurator:Check if runs as root. closes #5 feat:uhelper:Set mtd,tpm subsystem as /dev based

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -9,9 +9,9 @@ case "$1" in
     dpkg-trigger os-configurator-force
     ;;
   triggered)
-    if [ -x /opt/unipi/tools/os-configurator ]; then
+    if [ -x /usr/sbin/os-configurator ]; then
       echo "Calling os-configurator update..." >&2
-      ( /opt/unipi/tools/os-configurator --force && dpkg-trigger os-configurator-done ) || echo "os-configurator return error, please call it manually."
+      ( /usr/sbin/os-configurator --force && dpkg-trigger os-configurator-done ) || echo "os-configurator return error, please call it manually."
     fi
   ;;
 esac
