Fixed indent.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,21 +5,21 @@
 
 
 case "$1" in
-	triggered)
-	if [ -x /opt/unipi/tools/os-configurator ]; then
-		echo "Calling os-configurator update..." >&2
-		( /opt/unipi/tools/os-configurator --force && dpkg-trigger os-configurator-done ) || echo "os-configurator return error, please call it manually."
-	fi
-	;;
+  triggered)
+    if [ -x /opt/unipi/tools/os-configurator ]; then
+      echo "Calling os-configurator update..." >&2
+      ( /opt/unipi/tools/os-configurator --force && dpkg-trigger os-configurator-done ) || echo "os-configurator return error, please call it manually."
+    fi
+  ;;
 
   configure|abort-upgrade|abort-remove|abort-deconfigure)
     exit 0
   ;;
 
-	*)
-		echo "postinst called with unknown argument \`$1'" >&2
-		exit 1
-	;;
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
+  ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
